services:

  fastapi:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./migrations:/VehiclesMaintenanceDataAPI/migrations
      - ./src:/VehiclesMaintenanceDataAPI/src
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'

  postgresql:
    container_name: psql
    image: postgres:14.12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:



