"""Add unique constraints in vehicles

Revision ID: 064339c4ebde
Revises: a1d15261a4ba
Create Date: 2025-02-09 12:31:33.066975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064339c4ebde'
down_revision: Union[str, None] = 'a1d15261a4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['registration_number'])
    op.create_unique_constraint(None, 'vehicles', ['vin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
