"""Rename roleenum

Revision ID: 07965d49f4f1
Revises: 7893ce5f979a
Create Date: 2025-05-13 22:18:39.958689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07965d49f4f1'
down_revision: Union[str, None] = '7893ce5f979a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userroleenum = postgresql.ENUM('owner', 'worker', 'manager', 'admin', name='userroleenum')
    userroleenum.create(op.get_bind())

    op.alter_column('user_roles', 'role',
               existing_type=postgresql.ENUM('owner', 'worker', 'manager', 'admin', name='roleenum'),
               type_=userroleenum,
               postgresql_using='role::text::userroleenum',
               existing_nullable=False)

    op.execute('DROP TYPE IF EXISTS roleenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roleenum = postgresql.ENUM('owner', 'worker', 'manager', 'admin', name='roleenum')
    roleenum.create(op.get_bind())

    op.alter_column('user_roles', 'role',
               existing_type=sa.Enum('owner', 'worker', 'manager', 'admin', name='userroleenum'),
               type_=roleenum,
               postgresql_using='role::text::roleenum',  
               existing_nullable=False)
    
    op.execute('DROP TYPE IF EXISTS userroleenum')
    # ### end Alembic commands ###
