"""Add is email verified field in users

Revision ID: 0f1bdac0cd94
Revises: 78f9539869f1
Create Date: 2025-05-03 12:28:06.432382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1bdac0cd94'
down_revision: Union[str, None] = '78f9539869f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_email_verified = TRUE WHERE is_email_verified IS NULL")
    op.alter_column('users', 'is_email_verified', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
