"""Add created and updated fields

Revision ID: 147e46b7778c
Revises: 9e078d757f5e
Create Date: 2025-02-09 10:18:27.145090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147e46b7778c'
down_revision: Union[str, None] = '9e078d757f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('configurations', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('generations', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('generations', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('makes', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('makes', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('models', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('models', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('ranges', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('ranges', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranges', 'updated')
    op.drop_column('ranges', 'created')
    op.drop_column('models', 'updated')
    op.drop_column('models', 'created')
    op.drop_column('makes', 'updated')
    op.drop_column('makes', 'created')
    op.drop_column('generations', 'updated')
    op.drop_column('generations', 'created')
    op.drop_column('configurations', 'updated')
    op.drop_column('configurations', 'created')
    # ### end Alembic commands ###
