"""Add role enum field in user roles

Revision ID: 167e4067c23a
Revises: 4c7c07feadb9
Create Date: 2025-04-21 08:18:27.225129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '167e4067c23a'
down_revision: Union[str, None] = '4c7c07feadb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'role_id')
    op.drop_table('roles')
    op.add_column('user_roles', sa.Column('role', sa.Enum('owner', 'worker', 'manager', 'admin', name='roleenum'), nullable=False))
    op.create_unique_constraint(None, 'user_roles', ['role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', postgresql.ENUM('owner', 'worker', 'manager', 'admin', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_column('user_roles', 'role')
    op.add_column('user_roles', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])    
    # ### end Alembic commands ###
