"""Add enums in configurations

Revision ID: 212c340bd418
Revises: 17aa36a698b9
Create Date: 2025-02-02 21:50:47.367467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212c340bd418'
down_revision: Union[str, None] = '17aa36a698b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE enginetypeenum AS ENUM ('дизель', 'бензин', 'электричество', 'газ', 'газ/бензин');
    """)
    op.execute("""
        CREATE TYPE transmissionenum AS ENUM ('вариатор (CVT)', 'редуктор', 'робот', 'МКПП', 'АКПП');
    """)
    op.execute("""
        CREATE TYPE driveenum AS ENUM ('задний привод', 'передний привод', 'полный привод (4WD)');
    """)
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN engine_type 
        SET DATA TYPE enginetypeenum 
        USING engine_type::enginetypeenum;
    """)
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN transmission 
        SET DATA TYPE transmissionenum 
        USING transmission::transmissionenum;
    """)
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN drive 
        SET DATA TYPE driveenum 
        USING drive::driveenum;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN drive 
        SET DATA TYPE VARCHAR(30) 
        USING drive::VARCHAR(30) ;
    """)
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN transmission 
        SET DATA TYPE VARCHAR(30)  
        USING transmission::VARCHAR(30) ;
    """)
    op.execute("""
        ALTER TABLE configurations 
        ALTER COLUMN engine_type 
        SET DATA TYPE VARCHAR(30)  
        USING engine_type::VARCHAR(30) ;
    """)
    op.execute("DROP TYPE driveenum;")
    op.execute("DROP TYPE transmissionenum;")
    op.execute("DROP TYPE enginetypeenum;")
    # ### end Alembic commands ###
