"""Drop unuqiue constraint in models

Revision ID: 31f1e127adf2
Revises: e96c855d17cc
Create Date: 2025-01-30 13:55:56.153697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f1e127adf2'
down_revision: Union[str, None] = 'e96c855d17cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('models_name_key', 'models', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('models_name_key', 'models', ['name'])
    # ### end Alembic commands ###
