"""Add commercial name in services

Revision ID: 389db6e93d21
Revises: 36072a18d1e4
Create Date: 2025-05-14 10:41:07.197244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389db6e93d21'
down_revision: Union[str, None] = '36072a18d1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('commercial_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'commercial_name')
    # ### end Alembic commands ###
