"""Add ratings sum and count

Revision ID: 4ba254e4c6c3
Revises: 9e1c4fbe12fa
Create Date: 2025-05-24 15:28:27.689771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba254e4c6c3'
down_revision: Union[str, None] = '9e1c4fbe12fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_workers', sa.Column('ratings_sum', sa.Integer(), nullable=False))
    op.add_column('service_workers', sa.Column('ratings_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_workers', 'ratings_count')
    op.drop_column('service_workers', 'ratings_sum')
    # ### end Alembic commands ###
