"""Drop userroleenum

Revision ID: 4c7c07feadb9
Revises: 28ca46b20e2c
Create Date: 2025-04-13 21:26:28.845172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '4c7c07feadb9'
down_revision: Union[str, None] = '28ca46b20e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ENUM(name='userroleenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ENUM('owner', 'employee', name='userroleenum').create(op.get_bind())
    # ### end Alembic commands ###
