"""Add field photo_path in vehicles

Revision ID: 4cbd291abb10
Revises: a77836db3e73
Create Date: 2025-05-07 21:20:06.639259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbd291abb10'
down_revision: Union[str, None] = 'a77836db3e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'photo_path')
    # ### end Alembic commands ###
