"""Add maintenance record workers

Revision ID: 6402548a0895
Revises: dadb6adf50fd
Create Date: 2025-05-18 09:24:24.073086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6402548a0895'
down_revision: Union[str, None] = 'dadb6adf50fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_record_workers',
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['service_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_record_workers')
    # ### end Alembic commands ###
