"""Rename user id to worker id

Revision ID: 649891fa33f7
Revises: 4ba254e4c6c3
Create Date: 2025-05-24 16:56:48.050499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649891fa33f7'
down_revision: Union[str, None] = '4ba254e4c6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_workers', sa.Column('worker_id', sa.Integer(), nullable=False))
    op.drop_constraint('service_workers_user_id_fkey', 'service_workers', type_='foreignkey')
    op.create_foreign_key(None, 'service_workers', 'users', ['worker_id'], ['id'])
    op.drop_column('service_workers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_workers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_workers', type_='foreignkey')
    op.create_foreign_key('service_workers_user_id_fkey', 'service_workers', 'users', ['user_id'], ['id'])
    op.drop_column('service_workers', 'worker_id')
    # ### end Alembic commands ###
