"""Drop unique constr in role field

Revision ID: 6cb028d90110
Revises: 167e4067c23a
Create Date: 2025-04-21 08:32:00.147217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb028d90110'
down_revision: Union[str, None] = '167e4067c23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_role_key', 'user_roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_roles_role_key', 'user_roles', ['role'])
    # ### end Alembic commands ###
