"""Add manager id in table services

Revision ID: 78f9539869f1
Revises: 6cb028d90110
Create Date: 2025-04-22 11:00:34.789915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f9539869f1'
down_revision: Union[str, None] = '6cb028d90110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'manager_id')
    # ### end Alembic commands ###
