"""Alter string columns in users

Revision ID: 79e038b674b3
Revises: 2ef9bf77bdb6
Create Date: 2025-01-21 22:35:34.146572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '79e038b674b3'
down_revision: Union[str, None] = '2ef9bf77bdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.String(),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(),
                    type_=sa.String(length=60),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.String(length=255),
                    type_=sa.String(),
                    existing_nullable=False)
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(length=60),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###
