"""Add inn and ogrn in services

Revision ID: 7bf17ed8dd8f
Revises: 4cbd291abb10
Create Date: 2025-05-09 13:07:22.540192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf17ed8dd8f'
down_revision: Union[str, None] = '4cbd291abb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('inn', sa.String(length=12), nullable=False))
    op.add_column('services', sa.Column('ogrn', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'services', ['ogrn'])
    op.create_unique_constraint(None, 'services', ['inn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_column('services', 'ogrn')
    op.drop_column('services', 'inn')
    # ### end Alembic commands ###
