"""Fix tables for maintenance records

Revision ID: 8426e2dd3c03
Revises: 649891fa33f7
Create Date: 2025-05-24 18:50:23.430460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8426e2dd3c03'
down_revision: Union[str, None] = '649891fa33f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_record_workers',
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maintenance_record_service_workers')
    op.drop_constraint('maintenance_records_responsible_id_fkey', 'maintenance_records', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_records', 'users', ['responsible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.create_foreign_key('maintenance_records_responsible_id_fkey', 'maintenance_records', 'service_workers', ['responsible_id'], ['id'])
    op.create_table('maintenance_record_service_workers',
    sa.Column('maintenance_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], name='maintenance_record_service_workers_maintenance_record_id_fkey'),
    sa.ForeignKeyConstraint(['service_worker_id'], ['service_workers.id'], name='maintenance_record_service_workers_service_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenance_record_service_workers_pkey')
    )
    op.drop_table('maintenance_record_workers')
    # ### end Alembic commands ###
