"""Drop nullable constraints in configurations

Revision ID: 9e078d757f5e
Revises: 212c340bd418
Create Date: 2025-02-02 23:46:06.166817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e078d757f5e'
down_revision: Union[str, None] = '212c340bd418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurations', 'engine_power',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('configurations', 'engine_type',
               existing_type=postgresql.ENUM('дизель', 'бензин', 'электричество', 'газ', 'газ/бензин', name='enginetypeenum'),
               nullable=True)
    op.alter_column('configurations', 'transmission',
               existing_type=postgresql.ENUM('вариатор (CVT)', 'редуктор', 'робот', 'МКПП', 'АКПП', name='transmissionenum'),
               nullable=True)
    op.alter_column('configurations', 'drive',
               existing_type=postgresql.ENUM('задний привод', 'передний привод', 'полный привод (4WD)', name='driveenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configurations', 'drive',
               existing_type=postgresql.ENUM('задний привод', 'передний привод', 'полный привод (4WD)', name='driveenum'),
               nullable=False)
    op.alter_column('configurations', 'transmission',
               existing_type=postgresql.ENUM('вариатор (CVT)', 'редуктор', 'робот', 'МКПП', 'АКПП', name='transmissionenum'),
               nullable=False)
    op.alter_column('configurations', 'engine_type',
               existing_type=postgresql.ENUM('дизель', 'бензин', 'электричество', 'газ', 'газ/бензин', name='enginetypeenum'),
               nullable=False)
    op.alter_column('configurations', 'engine_power',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
