"""Add responsible_id

Revision ID: 9e1c4fbe12fa
Revises: a6d8c4ee9167
Create Date: 2025-05-23 11:19:02.480894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1c4fbe12fa'
down_revision: Union[str, None] = 'a6d8c4ee9167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('responsible_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'maintenance_records', 'service_workers', ['responsible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_column('maintenance_records', 'responsible_id')
    # ### end Alembic commands ###
