"""Add table vehicle

Revision ID: a1d15261a4ba
Revises: 147e46b7778c
Create Date: 2025-02-09 10:26:45.389106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d15261a4ba'
down_revision: Union[str, None] = '147e46b7778c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('range_id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('белый', 'бежевый', 'желтый', 'золотистый', 'оранжевый', 'розовый', 'красный', 'бордовый', 'зеленый', 'голубой', 'синий', 'фиолетовый', 'серый', 'серебристый', 'коричневый', 'черный', name='vehiclecolorenum'), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('registration_number', sa.String(length=9), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
