"""Drop responsible_id

Revision ID: a6d8c4ee9167
Revises: 58537468447a
Create Date: 2025-05-23 11:18:20.429792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d8c4ee9167'
down_revision: Union[str, None] = '58537468447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('maintenance_records_responsible_id_fkey', 'maintenance_records', type_='foreignkey')
    op.drop_column('maintenance_records', 'responsible_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('responsible_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('maintenance_records_responsible_id_fkey', 'maintenance_records', 'users', ['responsible_id'], ['id'])
    # ### end Alembic commands ###
