"""Rename field registration number

Revision ID: a77836db3e73
Revises: 0f1bdac0cd94
Create Date: 2025-05-07 20:16:50.663174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77836db3e73'
down_revision: Union[str, None] = '0f1bdac0cd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('registration_plate', sa.String(length=9), nullable=False))
    op.drop_constraint('vehicles_registration_number_key', 'vehicles', type_='unique')
    op.create_unique_constraint(None, 'vehicles', ['registration_plate'])
    op.drop_column('vehicles', 'registration_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('registration_number', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.create_unique_constraint('vehicles_registration_number_key', 'vehicles', ['registration_number'])
    op.drop_column('vehicles', 'registration_plate')
    # ### end Alembic commands ###
