"""Drop unique constraints in table users

Revision ID: a7ee6d51e25b
Revises: 79e038b674b3
Create Date: 2025-01-22 14:36:02.157514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ee6d51e25b'
down_revision: Union[str, None] = '79e038b674b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
