"""Drop table temp

Revision ID: b3928adc434d
Revises: b8cf8f9bfaec
Create Date: 2025-01-31 11:36:44.712220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3928adc434d'
down_revision: Union[str, None] = 'b8cf8f9bfaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('passenger', 'truck', name='modeltypeenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temp_pkey')
    )
    # ### end Alembic commands ###
