"""Add type field in models

Revision ID: b8cf8f9bfaec
Revises: 31f1e127adf2
Create Date: 2025-01-31 11:35:27.720524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cf8f9bfaec'
down_revision: Union[str, None] = '31f1e127adf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('passenger', 'truck', name='modeltypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('models', sa.Column('type', sa.Enum('passenger', 'truck', name='modeltypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'type')
    op.drop_table('temp')
    # ### end Alembic commands ###
