"""Rename table maintenance record workers

Revision ID: bfd45570e4c8
Revises: 892ede131e6a
Create Date: 2025-05-23 09:40:38.140804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd45570e4c8'
down_revision: Union[str, None] = '892ede131e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_record_service_workers',
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('service_worker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['service_worker_id'], ['service_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maintenance_record_workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_record_workers',
    sa.Column('maintenance_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], name='maintenance_record_workers_maintenance_record_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['service_workers.id'], name='maintenance_record_workers_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenance_record_workers_pkey')
    )
    op.drop_table('maintenance_record_service_workers')
    # ### end Alembic commands ###
