"""Add tables for vehicles data

Revision ID: e96c855d17cc
Revises: a7ee6d51e25b
Create Date: 2025-01-25 17:08:59.473345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96c855d17cc'
down_revision: Union[str, None] = 'a7ee6d51e25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=False),
    sa.Column('vehicle_body', sa.String(length=30), nullable=False),
    sa.Column('range_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_capacity', sa.Float(), nullable=False),
    sa.Column('engine_power', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.String(length=30), nullable=False),
    sa.Column('transmission', sa.String(length=30), nullable=False),
    sa.Column('drive', sa.String(length=30), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    op.drop_table('generations')
    op.drop_table('ranges')
    op.drop_table('models')
    op.drop_table('makes')
    # ### end Alembic commands ###
