"""Alter column phone

Revision ID: ed7245ce127a
Revises: 36b97d68d03c
Create Date: 2025-01-11 14:59:49.001949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7245ce127a'
down_revision: Union[str, None] = '36b97d68d03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.CHAR(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.CHAR(length=18),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###
