"""Rename user_id to owner_id

Revision ID: f25fb058ee5a
Revises: 802bf653204e
Create Date: 2025-05-17 22:31:39.023343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25fb058ee5a'
down_revision: Union[str, None] = '802bf653204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('vehicles_user_id_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['owner_id'], ['id'])
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_user_id_fkey', 'vehicles', 'users', ['user_id'], ['id'])
    op.drop_column('vehicles', 'owner_id')
    # ### end Alembic commands ###
